# Generated by Django 5.2.1 on 2025-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("static_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemetry",
            name="drs",
            field=models.IntegerField(null=True),
        ),
    ]
