# Generated by Django 5.2.1 on 2025-05-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("static_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="constructorcolor",
            old_name="constructor_name",
            new_name="constructor",
        ),
    ]
