# Generated by Django 5.2 on 2025-05-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="middle_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
