# Generated by Django 5.2 on 2025-05-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_driver_middle_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="middle_name",
        ),
    ]
