# Generated by Django 5.2 on 2025-05-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_remove_driver_middle_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cardata",
            index=models.Index(fields=["lap"], name="idx_car_data_lap"),
        ),
        migrations.AddIndex(
            model_name="positiondata",
            index=models.Index(fields=["lap"], name="idx_pos_data_lap"),
        ),
        migrations.AddIndex(
            model_name="telemetry",
            index=models.Index(fields=["lap"], name="idx_telemetry_lap"),
        ),
    ]
